config/routes.rb
Rails.application.routes.draw do
  resources :parents

  resources :childdfs

  resources :childdssses

end

app/models/childdf.rb
class Childdf < ActiveRecord::Base
  belongs_to :parent
  has_many :childdssses
end

app/models/childdsss.rb
class Childdsss < ActiveRecord::Base
  belongs_to :childdf
end

app/models/parent.rb
class Parent < ActiveRecord::Base
  has_one :childdf
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/childdfs_controller.rb
class ChilddfsController < ApplicationController
  before_action :set_childdf, only: [:show, :edit, :update, :destroy]

  # GET /childdfs
  # GET /childdfs.json
  def index
    @childdfs = Childdf.all
  end

  # GET /childdfs/1
  # GET /childdfs/1.json
  def show
  end

  # GET /childdfs/new
  def new
    @childdf = Childdf.new
  end

  # GET /childdfs/1/edit
  def edit
  end

  # POST /childdfs
  # POST /childdfs.json
  def create
    @childdf = Childdf.new(childdf_params)

    respond_to do |format|
      if @childdf.save
        format.html { redirect_to @childdf, notice: 'Childdf was successfully created.' }
        format.json { render :show, status: :created, location: @childdf }
      else
        format.html { render :new }
        format.json { render json: @childdf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /childdfs/1
  # PATCH/PUT /childdfs/1.json
  def update
    respond_to do |format|
      if @childdf.update(childdf_params)
        format.html { redirect_to @childdf, notice: 'Childdf was successfully updated.' }
        format.json { render :show, status: :ok, location: @childdf }
      else
        format.html { render :edit }
        format.json { render json: @childdf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /childdfs/1
  # DELETE /childdfs/1.json
  def destroy
    @childdf.destroy
    respond_to do |format|
      format.html { redirect_to childdfs_url, notice: 'Childdf was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_childdf
      @childdf = Childdf.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def childdf_params
      params.require(:childdf).permit(:name, :parent_id)
    end
end

app/controllers/childdssses_controller.rb
class ChilddsssesController < ApplicationController
  before_action :set_childdsss, only: [:show, :edit, :update, :destroy]

  # GET /childdssses
  # GET /childdssses.json
  def index
    @childdssses = Childdsss.all
  end

  # GET /childdssses/1
  # GET /childdssses/1.json
  def show
  end

  # GET /childdssses/new
  def new
    @childdsss = Childdsss.new
  end

  # GET /childdssses/1/edit
  def edit
  end

  # POST /childdssses
  # POST /childdssses.json
  def create
    @childdsss = Childdsss.new(childdsss_params)

    respond_to do |format|
      if @childdsss.save
        format.html { redirect_to @childdsss, notice: 'Childdsss was successfully created.' }
        format.json { render :show, status: :created, location: @childdsss }
      else
        format.html { render :new }
        format.json { render json: @childdsss.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /childdssses/1
  # PATCH/PUT /childdssses/1.json
  def update
    respond_to do |format|
      if @childdsss.update(childdsss_params)
        format.html { redirect_to @childdsss, notice: 'Childdsss was successfully updated.' }
        format.json { render :show, status: :ok, location: @childdsss }
      else
        format.html { render :edit }
        format.json { render json: @childdsss.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /childdssses/1
  # DELETE /childdssses/1.json
  def destroy
    @childdsss.destroy
    respond_to do |format|
      format.html { redirect_to childdssses_url, notice: 'Childdsss was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_childdsss
      @childdsss = Childdsss.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def childdsss_params
      params.require(:childdsss).permit(:childdf_id)
    end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action :set_parent, only: [:show, :edit, :update, :destroy]

  # GET /parents
  # GET /parents.json
  def index
    @parents = Parent.all
  end

  # GET /parents/1
  # GET /parents/1.json
  def show
  end

  # GET /parents/new
  def new
    @parent = Parent.new
  end

  # GET /parents/1/edit
  def edit
  end

  # POST /parents
  # POST /parents.json
  def create
    @parent = Parent.new(parent_params)

    respond_to do |format|
      if @parent.save
        format.html { redirect_to @parent, notice: 'Parent was successfully created.' }
        format.json { render :show, status: :created, location: @parent }
      else
        format.html { render :new }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parents/1
  # PATCH/PUT /parents/1.json
  def update
    respond_to do |format|
      if @parent.update(parent_params)
        format.html { redirect_to @parent, notice: 'Parent was successfully updated.' }
        format.json { render :show, status: :ok, location: @parent }
      else
        format.html { render :edit }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parents/1
  # DELETE /parents/1.json
  def destroy
    @parent.destroy
    respond_to do |format|
      format.html { redirect_to parents_url, notice: 'Parent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parent
      @parent = Parent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parent_params
      params.require(:parent).permit(:fdasa)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/childdfs_helper.rb
module ChilddfsHelper
end

app/helpers/childdssses_helper.rb
module ChilddsssesHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/views/childdfs/_form.html.erb
<%= simple_form_for(@childdf) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :parent %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/childdfs/edit.html.erb
<h1>Editing childdf</h1>

<%= render 'form' %>

<%= link_to 'Show', @childdf %> |
<%= link_to 'Back', childdfs_path %>

app/views/childdfs/index.html.erb
<h1>Listing childdfs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @childdfs.each do |childdf| %>
      <tr>
        <td><%= childdf.name %></td>
        <td><%= childdf.parent %></td>
        <td><%= link_to 'Show', childdf %></td>
        <td><%= link_to 'Edit', edit_childdf_path(childdf) %></td>
        <td><%= link_to 'Destroy', childdf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Childdf', new_childdf_path %>

app/views/childdfs/new.html.erb
<h1>New childdf</h1>

<%= render 'form' %>

<%= link_to 'Back', childdfs_path %>

app/views/childdfs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @childdf.name %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @childdf.parent %>
</p>

<%= link_to 'Edit', edit_childdf_path(@childdf) %> |
<%= link_to 'Back', childdfs_path %>

app/views/childdssses/_form.html.erb
<%= simple_form_for(@childdsss) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :childdf %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/childdssses/edit.html.erb
<h1>Editing childdsss</h1>

<%= render 'form' %>

<%= link_to 'Show', @childdsss %> |
<%= link_to 'Back', childdssses_path %>

app/views/childdssses/index.html.erb
<h1>Listing childdssses</h1>

<table>
  <thead>
    <tr>
      <th>Childdf</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @childdssses.each do |childdsss| %>
      <tr>
        <td><%= childdsss.childdf %></td>
        <td><%= link_to 'Show', childdsss %></td>
        <td><%= link_to 'Edit', edit_childdsss_path(childdsss) %></td>
        <td><%= link_to 'Destroy', childdsss, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Childdsss', new_childdsss_path %>

app/views/childdssses/new.html.erb
<h1>New childdsss</h1>

<%= render 'form' %>

<%= link_to 'Back', childdssses_path %>

app/views/childdssses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Childdf:</strong>
  <%= @childdsss.childdf %>
</p>

<%= link_to 'Edit', edit_childdsss_path(@childdsss) %> |
<%= link_to 'Back', childdssses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gcxzvcxz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/parents/_form.html.erb
<%= simple_form_for(@parent) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :fdasa %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/parents/edit.html.erb
<h1>Editing parent</h1>

<%= render 'form' %>

<%= link_to 'Show', @parent %> |
<%= link_to 'Back', parents_path %>

app/views/parents/index.html.erb
<h1>Listing parents</h1>

<table>
  <thead>
    <tr>
      <th>Fdasa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parents.each do |parent| %>
      <tr>
        <td><%= parent.fdasa %></td>
        <td><%= link_to 'Show', parent %></td>
        <td><%= link_to 'Edit', edit_parent_path(parent) %></td>
        <td><%= link_to 'Destroy', parent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parent', new_parent_path %>

app/views/parents/new.html.erb
<h1>New parent</h1>

<%= render 'form' %>

<%= link_to 'Back', parents_path %>

app/views/parents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fdasa:</strong>
  <%= @parent.fdasa %>
</p>

<%= link_to 'Edit', edit_parent_path(@parent) %> |
<%= link_to 'Back', parents_path %>